CREATE TABLE USUARIO(
	COD_USUARIO SERIAL PRIMARY KEY,
	NOME VARCHAR(40) NOT NULL,
	EMAIL VARCHAR(60) NOT NULL,
	SENHA VARCHAR(255) NOT NULL
);

CREATE TABLE POSTAGEM(
	COD_POSTAGEM SERIAL PRIMARY KEY,
	TITULO VARCHAR(60) NOT NULL,
	CONTEUDO TEXT NOT NULL,
	DATA_POSTAGEM DATE NOT NULL DEFAULT current_date,
	COD_USUARIO INT NOT NULL REFERENCES USUARIO(COD_USUARIO)
);

CREATE TABLE COMENTARIO(
	COD_COMENTARIO SERIAL PRIMARY KEY,
	COD_USUARIO INT NOT NULL REFERENCES USUARIO(COD_USUARIO),
	COD_POSTAGEM INT NOT NULL REFERENCES POSTAGEM(COD_POSTAGEM),
	COMENTARIO TEXT NOT NULL
);

INSERT INTO USUARIO(NOME,EMAIL,SENHA) VALUES('nemesis','nemesis@email.com','nemesis');
INSERT INTO POSTAGEM(TITULO,CONTEUDO,COD_USUARIO) VALUES('Primeira postagem','nada alem da primeira postagem...',1);

SELECT * FROM USUARIO;
SELECT * FROM POSTAGEM;
SELECT * FROM COMENTARIO;

SELECT USUARIO.NOME,POSTAGEM.COD_POSTAGEM FROM USUARIO INNER JOIN POSTAGEM ON USUARIO.COD_USUARIO = POSTAGEM.COD_USUARIO;
SELECT current_date, current_time, current_timestamp;

DROP TABLE USUARIO;
DROP TABLE POSTAGEM;
DROP TABLE COMENTARIO;

